### ISSUE TITLE
New Quote Button not responding

### ISSUE THREAD

**Issue by georgeben** [Kolokodess/Inspirikoko-#1]
Hello @Kolokodess I cloned your repo, but when I run it on my browser - google chrome, the "New Quote" button does not respond.

**Comment by hemmayo** [comment]
Check **js/inspirikoko.js** line 6. The url is _http://cors-escape.herokuapp.com/https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=json_

**http://cors-escape.herokuapp.com/** says "No such app". 
**https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=json** works through my browser but not with AJAX.

**Current issue is this:** Failed to load https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8082' is therefore not allowed access.

**Comment by hemmayo** [comment]
**Bug fix:**
**js/inspirikoko.js:6** Replace  _http://cors-escape.herokuapp.com/https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=json_ with  **https://cors-anywhere.herokuapp.com/https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=json**
